using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using TenantFlowERP.Data;

namespace TenantFlowERP.Services
{
    public class InvoicePdfService
    {
        private readonly AppDbContext _context;

        public InvoicePdfService(AppDbContext context)
        {
            _context = context;
        }

        public async Task<byte[]> GenerateInvoicePdf(Guid invoiceId)
        {
            var invoice = await _context.Invoices
                .Include(x => x.Customer)
                .Include(x => x.Items)
                .ThenInclude(x => x.Product)
                .FirstOrDefaultAsync(x => x.Id == invoiceId);

            if (invoice == null)
            {
                throw new Exception("Invoice not found");
            }

            var pdf = Document.Create(container =>
            {
            container.Page(page =>
            {
            page.Margin(30);

            page.Header()
                .Text("TenantFlow ERP Invoice")
                .FontSize(24)
                .Bold();

            page.Content()
                .Column(col => {
                    col.Spacing(10);

                    col.Item().Text($"Invoice Number: {invoice.InvoiceNumber}");

                    col.Item().Text($"Customer: {invoice.Customer.Name}");

                    col.Item().Text($"Date: {invoice.CreatedAt:dd-MM-yyyy}");

                    col.Item().LineHorizontal(1);

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        // HEADER
                        table.Header(header =>
                        {
                            header.Cell().Text("Product").Bold();
                            header.Cell().Text("Qty").Bold();
                            header.Cell().Text("Price").Bold();
                            header.Cell().Text("Total").Bold();
                        });

                        // ROWS
                        foreach (var item in invoice.Items)
                        {
                            table.Cell().Text(item.Product.Name);

                            table.Cell().Text(item.Quantity.ToString());

                            table.Cell().Text(item.Price.ToString());

                            table.Cell().Text(item.Total.ToString());
                        }
                    });

                    col.Item().LineHorizontal(1);

                    col.Item()
                        .AlignRight()
                        .Text($"Grand Total: ₹{invoice.TotalAmount}")
                        .FontSize(18)
                        .Bold();
                });
                page.Footer()
                                     .AlignCenter()
                                     .Text(x =>
                                     {
                                         x.Span("Generated by TenantFlow ERP");
                                     });
            });
            }).GeneratePdf();

            return pdf;
        }
    }
}